### ISSUE TITLE
Issue with install 1.17

### ISSUE THREAD

**Issue by julianrinaldi** [vigonotion/hass-simpleicons#111]
Version 1.17 deletes the simpleicons folder from the custom_components folder when installing it. Installing 1.16 again recreates it without issue.

**Comment by Jefe2** [comment]
Same issue here as well.

**Comment by kaizersoje** [comment]
Same issue here as well.

**Comment by julianrinaldi** [comment]
Sorry, I should mention the install was failing via HACS. Manually installing 1.17 gives this error below, however, I just upgraded to the prerelease of 2021.5.0b1, so I don't know if manually installing gave an error on 2021.4.6 or not.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/simpleicons/__init__.py:52
Integration: Simple Icons (documentation)
First occurred: 7:48:32 PM (1 occurrences)
Last logged: 7:48:32 PM

Error setting up entry for simpleicons
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/Users/homeassistant/.homeassistant/custom_components/simpleicons/__init__.py", line 34, in async_setup_entry
    register_modules(hass)
  File "/Users/homeassistant/.homeassistant/custom_components/simpleicons/__init__.py", line 52, in register_modules
    url_set.discard(ICONS_URL+v)
AttributeError: 'UrlManager' object has no attribute 'discard'
```

**Comment by joostvkempen** [comment]
same issue, using HACS

**Comment by vigonotion** [comment]
Thanks for reporting this! It should be fixed in v1.18.0.

**Comment by kaizersoje** [comment]
Thanks for fixing this. However, this version requires a minimum version of 2021.5.x which is not production yet. I am unable to install this version as I have v2021.4.6 installed.

**Comment by vigonotion** [comment]
Can you download the zip and install the integration manually and try if it works on 2021.4.6? If yes I will release a new version with that version as min version

**Comment by julianrinaldi** [comment]
I'm on 2021.5.0b1 and I was able to manually install it and it works. Trying to install it through HACS failed though. It deleted the simpleicons folder and it was never recreated.

**Comment by vigonotion** [comment]
Please update to v1.18.3. Should be fixed now
